default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: akp

development:
  <<: *default
  host: localhost
  database: akp
  username: root
  password:

production:
  <<: *default
  host: localhost
  database: ash
