default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: akp

development:
  <<: *default
  host: localhost
  database: akp
  username: root
  password:

production:
  <<: *default
  host: localhost
  database: ash

staging:
    <<: *default
    host: localhost
    database: akp
    user: akp
    password: E#E0J1uQ0ZJX5s
