default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: akp
  username: root
  password:

production:
  <<: *default
  host: localhost
  username: akp_p_user
  password: calculi72
  database: akp_production

staging:
  <<: *default
  host: localhost
  database: akp
  username: akp
  password: E#E0J1uQ0ZJX5s
